package com;

import java.io.File;
import java.io.IOException;
import java.io.StringReader;
import java.nio.file.Path;
import java.nio.file.Paths;

import javax.xml.XMLConstants;
import javax.xml.transform.stream.StreamSource;
import javax.xml.validation.Schema;
import javax.xml.validation.SchemaFactory;
import javax.xml.validation.Validator;

import org.xml.sax.SAXException;

import com.basic.ClipboardUtils;

import common.util.Base64Utils;

public class Main {

	public void test() {
		Path path = Paths.get("C:/Users/huyennv/Desktop/tax-conver/833_04_TNDN_TT80_2022.xlsx");
		String base64 = Base64Utils.encodeToString(path);
		System.out.println(base64.trim());
		ClipboardUtils.copy(base64);
	}

	public static void validateXMLSchemaStringXML(String xsdPath, String xml) {
		try {
			SchemaFactory factory = SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);
			Schema schema = factory.newSchema(new File(xsdPath));
			Validator validator = schema.newValidator();
			StreamSource source = new StreamSource(new StringReader(xml));
			validator.validate(source);
		} catch (SAXException | IOException e) {
			e.printStackTrace();
		}
	}

	public static void main(String[] args) {
		String xsd = "D:/ts24corp/workspace/ts24projects/excel2xml_thue/src/main/resources/xsd/TK1-TS.xsd";
		String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><TK1-TS xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"file:///C:/Users/tramntn/Desktop/Excel_Tax_BH/iBHXH/XML/600-TK01-TS.xsd\">\r\n"
				+ "	<NoiDung>\r\n"
				+ "		<LaoDong>\r\n"
				+ "			<STT>1</STT>\r\n"
				+ "			<HoTen>0</HoTen>\r\n"
				+ "			<NgaySinh>19/03/2000</NgaySinh>\r\n"
				+ "			<GioiTinh>1</GioiTinh>\r\n"
				+ "			<DanToc>01</DanToc>\r\n"
				+ "			<QuocTich>VN</QuocTich>\r\n"
				+ "			<Matinh_KS>01</Matinh_KS>\r\n"
				+ "			<Mahuyen_KS>282</Mahuyen_KS>\r\n"
				+ "			<Maxa_KS>10477</Maxa_KS>\r\n"
				+ "			<Diachi_NN>0</Diachi_NN>\r\n"
				+ "			<Matinh_NN>01</Matinh_NN>\r\n"
				+ "			<Mahuyen_NN>282</Mahuyen_NN>\r\n"
				+ "			<Maxa_NN>10477</Maxa_NN>\r\n"
				+ "			<Diachi_KS>0</Diachi_KS>\r\n"
				+ "			<Ten_ChaMe_Giamho>0</Ten_ChaMe_Giamho>\r\n"
				+ "			<MasoBHXH>123</MasoBHXH>\r\n"
				+ "			<Dienthoai_LH>0</Dienthoai_LH>\r\n"
				+ "			<Email_LH>0</Email_LH>\r\n"
				+ "			<CMND>0</CMND>\r\n"
				+ "			<Maho_Giadinh>0</Maho_Giadinh>\r\n"
				+ "			<Mucdong>0</Mucdong>\r\n"
				+ "			<Phuongthuc xsi:nil=\"true\"/>\r\n"
				+ "			<MaTinhBenhVien>01</MaTinhBenhVien>\r\n"
				+ "			<MaBenhVien>P02</MaBenhVien>\r\n"
				+ "			<Noidung_Thaydoi>0</Noidung_Thaydoi>\r\n"
				+ "			<HosoKemtheo>0</HosoKemtheo>\r\n"
				+ "			<CCNS>0</CCNS>\r\n"
				+ "			<ID>0000000001</ID>\r\n"
				+ "			<PhuLuc/>\r\n"
				+ "		</LaoDong>\r\n"
				+ "		<LaoDong>\r\n"
				+ "			<STT>2</STT>\r\n"
				+ "			<HoTen>0</HoTen>\r\n"
				+ "			<NgaySinh>19/03/2000</NgaySinh>\r\n"
				+ "			<GioiTinh>1</GioiTinh>\r\n"
				+ "			<DanToc>01</DanToc>\r\n"
				+ "			<QuocTich>VN</QuocTich>\r\n"
				+ "			<Matinh_KS>01</Matinh_KS>\r\n"
				+ "			<Mahuyen_KS>016</Mahuyen_KS>\r\n"
				+ "			<Maxa_KS>00409</Maxa_KS>\r\n"
				+ "			<Diachi_NN>0</Diachi_NN>\r\n"
				+ "			<Matinh_NN>01</Matinh_NN>\r\n"
				+ "			<Mahuyen_NN>016</Mahuyen_NN>\r\n"
				+ "			<Maxa_NN>00409</Maxa_NN>\r\n"
				+ "			<Diachi_KS>0</Diachi_KS>\r\n"
				+ "			<Ten_ChaMe_Giamho>0</Ten_ChaMe_Giamho>\r\n"
				+ "			<MasoBHXH>124</MasoBHXH>\r\n"
				+ "			<Dienthoai_LH>0</Dienthoai_LH>\r\n"
				+ "			<Email_LH>0</Email_LH>\r\n"
				+ "			<CMND>0</CMND>\r\n"
				+ "			<Maho_Giadinh>0</Maho_Giadinh>\r\n"
				+ "			<Mucdong>0</Mucdong>\r\n"
				+ "			<Phuongthuc xsi:nil=\"true\"/>\r\n"
				+ "			<MaTinhBenhVien>01</MaTinhBenhVien>\r\n"
				+ "			<MaBenhVien>P03</MaBenhVien>\r\n"
				+ "			<Noidung_Thaydoi>0</Noidung_Thaydoi>\r\n"
				+ "			<HosoKemtheo>0</HosoKemtheo>\r\n"
				+ "			<CCNS>0</CCNS>\r\n"
				+ "			<ID>0000000002</ID>\r\n"
				+ "			<PhuLuc/>\r\n"
				+ "		</LaoDong>\r\n"
				+ "		<LaoDong>\r\n"
				+ "			<STT>3</STT>\r\n"
				+ "			<HoTen>0</HoTen>\r\n"
				+ "			<NgaySinh>19/03/2000</NgaySinh>\r\n"
				+ "			<GioiTinh>1</GioiTinh>\r\n"
				+ "			<DanToc>01</DanToc>\r\n"
				+ "			<QuocTich>VN</QuocTich>\r\n"
				+ "			<Matinh_KS>01</Matinh_KS>\r\n"
				+ "			<Mahuyen_KS>002</Mahuyen_KS>\r\n"
				+ "			<Maxa_KS>00055</Maxa_KS>\r\n"
				+ "			<Diachi_NN>0</Diachi_NN>\r\n"
				+ "			<Matinh_NN>01</Matinh_NN>\r\n"
				+ "			<Mahuyen_NN>002</Mahuyen_NN>\r\n"
				+ "			<Maxa_NN>00055</Maxa_NN>\r\n"
				+ "			<Diachi_KS>0</Diachi_KS>\r\n"
				+ "			<Ten_ChaMe_Giamho>0</Ten_ChaMe_Giamho>\r\n"
				+ "			<MasoBHXH>125</MasoBHXH>\r\n"
				+ "			<Dienthoai_LH>0</Dienthoai_LH>\r\n"
				+ "			<Email_LH>0</Email_LH>\r\n"
				+ "			<CMND>0</CMND>\r\n"
				+ "			<Maho_Giadinh>0</Maho_Giadinh>\r\n"
				+ "			<Mucdong>0</Mucdong>\r\n"
				+ "			<Phuongthuc xsi:nil=\"true\"/>\r\n"
				+ "			<MaTinhBenhVien>01</MaTinhBenhVien>\r\n"
				+ "			<MaBenhVien>P04</MaBenhVien>\r\n"
				+ "			<Noidung_Thaydoi>0</Noidung_Thaydoi>\r\n"
				+ "			<HosoKemtheo>0</HosoKemtheo>\r\n"
				+ "			<CCNS>0</CCNS>\r\n"
				+ "			<ID>0000000003</ID>\r\n"
				+ "			<PhuLuc/>\r\n"
				+ "		</LaoDong>\r\n"
				+ "		<LaoDong>\r\n"
				+ "			<STT>4</STT>\r\n"
				+ "			<HoTen>0</HoTen>\r\n"
				+ "			<NgaySinh>19/03/2000</NgaySinh>\r\n"
				+ "			<GioiTinh>1</GioiTinh>\r\n"
				+ "			<DanToc>01</DanToc>\r\n"
				+ "			<QuocTich>VN</QuocTich>\r\n"
				+ "			<Matinh_KS>02</Matinh_KS>\r\n"
				+ "			<Mahuyen_KS>033</Mahuyen_KS>\r\n"
				+ "			<Maxa_KS>01135</Maxa_KS>\r\n"
				+ "			<Diachi_NN>0</Diachi_NN>\r\n"
				+ "			<Matinh_NN>02</Matinh_NN>\r\n"
				+ "			<Mahuyen_NN>033</Mahuyen_NN>\r\n"
				+ "			<Maxa_NN>01135</Maxa_NN>\r\n"
				+ "			<Diachi_KS>0</Diachi_KS>\r\n"
				+ "			<Ten_ChaMe_Giamho>0</Ten_ChaMe_Giamho>\r\n"
				+ "			<MasoBHXH>126</MasoBHXH>\r\n"
				+ "			<Dienthoai_LH>0</Dienthoai_LH>\r\n"
				+ "			<Email_LH>0</Email_LH>\r\n"
				+ "			<CMND>0</CMND>\r\n"
				+ "			<Maho_Giadinh>0</Maho_Giadinh>\r\n"
				+ "			<Mucdong>0</Mucdong>\r\n"
				+ "			<Phuongthuc xsi:nil=\"true\"/>\r\n"
				+ "			<MaTinhBenhVien>01</MaTinhBenhVien>\r\n"
				+ "			<MaBenhVien>P05</MaBenhVien>\r\n"
				+ "			<Noidung_Thaydoi>0</Noidung_Thaydoi>\r\n"
				+ "			<HosoKemtheo>0</HosoKemtheo>\r\n"
				+ "			<CCNS>0</CCNS>\r\n"
				+ "			<ID>0000000004</ID>\r\n"
				+ "			<PhuLuc/>\r\n"
				+ "		</LaoDong>\r\n"
				+ "		<LaoDong>\r\n"
				+ "			<STT>5</STT>\r\n"
				+ "			<HoTen>0</HoTen>\r\n"
				+ "			<NgaySinh>19/03/2000</NgaySinh>\r\n"
				+ "			<GioiTinh>1</GioiTinh>\r\n"
				+ "			<DanToc>01</DanToc>\r\n"
				+ "			<QuocTich>VN</QuocTich>\r\n"
				+ "			<Matinh_KS>01</Matinh_KS>\r\n"
				+ "			<Mahuyen_KS>282</Mahuyen_KS>\r\n"
				+ "			<Maxa_KS>10477</Maxa_KS>\r\n"
				+ "			<Diachi_NN>0</Diachi_NN>\r\n"
				+ "			<Matinh_NN>01</Matinh_NN>\r\n"
				+ "			<Mahuyen_NN>282</Mahuyen_NN>\r\n"
				+ "			<Maxa_NN>10477</Maxa_NN>\r\n"
				+ "			<Diachi_KS>0</Diachi_KS>\r\n"
				+ "			<Ten_ChaMe_Giamho>0</Ten_ChaMe_Giamho>\r\n"
				+ "			<MasoBHXH>127</MasoBHXH>\r\n"
				+ "			<Dienthoai_LH>0</Dienthoai_LH>\r\n"
				+ "			<Email_LH>0</Email_LH>\r\n"
				+ "			<CMND>0</CMND>\r\n"
				+ "			<Maho_Giadinh>0</Maho_Giadinh>\r\n"
				+ "			<Mucdong>0</Mucdong>\r\n"
				+ "			<Phuongthuc xsi:nil=\"true\"/>\r\n"
				+ "			<MaTinhBenhVien>01</MaTinhBenhVien>\r\n"
				+ "			<MaBenhVien>P06</MaBenhVien>\r\n"
				+ "			<Noidung_Thaydoi>0</Noidung_Thaydoi>\r\n"
				+ "			<HosoKemtheo>0</HosoKemtheo>\r\n"
				+ "			<CCNS>0</CCNS>\r\n"
				+ "			<ID>0000000005</ID>\r\n"
				+ "			<PhuLuc/>\r\n"
				+ "		</LaoDong>\r\n"
				+ "		<LaoDong>\r\n"
				+ "			<STT>6</STT>\r\n"
				+ "			<HoTen>0</HoTen>\r\n"
				+ "			<NgaySinh>19/03/2000</NgaySinh>\r\n"
				+ "			<GioiTinh>1</GioiTinh>\r\n"
				+ "			<DanToc>01</DanToc>\r\n"
				+ "			<QuocTich>VN</QuocTich>\r\n"
				+ "			<Matinh_KS>01</Matinh_KS>\r\n"
				+ "			<Mahuyen_KS>016</Mahuyen_KS>\r\n"
				+ "			<Maxa_KS>00409</Maxa_KS>\r\n"
				+ "			<Diachi_NN>0</Diachi_NN>\r\n"
				+ "			<Matinh_NN>01</Matinh_NN>\r\n"
				+ "			<Mahuyen_NN>016</Mahuyen_NN>\r\n"
				+ "			<Maxa_NN>00409</Maxa_NN>\r\n"
				+ "			<Diachi_KS>0</Diachi_KS>\r\n"
				+ "			<Ten_ChaMe_Giamho>0</Ten_ChaMe_Giamho>\r\n"
				+ "			<MasoBHXH>128</MasoBHXH>\r\n"
				+ "			<Dienthoai_LH>0</Dienthoai_LH>\r\n"
				+ "			<Email_LH>0</Email_LH>\r\n"
				+ "			<CMND>0</CMND>\r\n"
				+ "			<Maho_Giadinh>0</Maho_Giadinh>\r\n"
				+ "			<Mucdong>0</Mucdong>\r\n"
				+ "			<Phuongthuc xsi:nil=\"true\"/>\r\n"
				+ "			<MaTinhBenhVien>01</MaTinhBenhVien>\r\n"
				+ "			<MaBenhVien>P07</MaBenhVien>\r\n"
				+ "			<Noidung_Thaydoi>0</Noidung_Thaydoi>\r\n"
				+ "			<HosoKemtheo>0</HosoKemtheo>\r\n"
				+ "			<CCNS>0</CCNS>\r\n"
				+ "			<ID>0000000006</ID>\r\n"
				+ "			<PhuLuc/>\r\n"
				+ "		</LaoDong>\r\n"
				+ "		<LaoDong>\r\n"
				+ "			<STT>7</STT>\r\n"
				+ "			<HoTen>0</HoTen>\r\n"
				+ "			<NgaySinh>19/03/2000</NgaySinh>\r\n"
				+ "			<GioiTinh>1</GioiTinh>\r\n"
				+ "			<DanToc>01</DanToc>\r\n"
				+ "			<QuocTich>VN</QuocTich>\r\n"
				+ "			<Matinh_KS>01</Matinh_KS>\r\n"
				+ "			<Mahuyen_KS>002</Mahuyen_KS>\r\n"
				+ "			<Maxa_KS>00055</Maxa_KS>\r\n"
				+ "			<Diachi_NN>0</Diachi_NN>\r\n"
				+ "			<Matinh_NN>01</Matinh_NN>\r\n"
				+ "			<Mahuyen_NN>002</Mahuyen_NN>\r\n"
				+ "			<Maxa_NN>00055</Maxa_NN>\r\n"
				+ "			<Diachi_KS>0</Diachi_KS>\r\n"
				+ "			<Ten_ChaMe_Giamho>0</Ten_ChaMe_Giamho>\r\n"
				+ "			<MasoBHXH>129</MasoBHXH>\r\n"
				+ "			<Dienthoai_LH>0</Dienthoai_LH>\r\n"
				+ "			<Email_LH>0</Email_LH>\r\n"
				+ "			<CMND>0</CMND>\r\n"
				+ "			<Maho_Giadinh>0</Maho_Giadinh>\r\n"
				+ "			<Mucdong>0</Mucdong>\r\n"
				+ "			<Phuongthuc xsi:nil=\"true\"/>\r\n"
				+ "			<MaTinhBenhVien>01</MaTinhBenhVien>\r\n"
				+ "			<MaBenhVien>P08</MaBenhVien>\r\n"
				+ "			<Noidung_Thaydoi>0</Noidung_Thaydoi>\r\n"
				+ "			<HosoKemtheo>0</HosoKemtheo>\r\n"
				+ "			<CCNS>0</CCNS>\r\n"
				+ "			<ID>0000000007</ID>\r\n"
				+ "			<PhuLuc/>\r\n"
				+ "		</LaoDong>\r\n"
				+ "		<LaoDong>\r\n"
				+ "			<STT>8</STT>\r\n"
				+ "			<HoTen>0</HoTen>\r\n"
				+ "			<NgaySinh>19/03/2000</NgaySinh>\r\n"
				+ "			<GioiTinh>1</GioiTinh>\r\n"
				+ "			<DanToc>01</DanToc>\r\n"
				+ "			<QuocTich>VN</QuocTich>\r\n"
				+ "			<Matinh_KS>02</Matinh_KS>\r\n"
				+ "			<Mahuyen_KS>033</Mahuyen_KS>\r\n"
				+ "			<Maxa_KS>01135</Maxa_KS>\r\n"
				+ "			<Diachi_NN>0</Diachi_NN>\r\n"
				+ "			<Matinh_NN>02</Matinh_NN>\r\n"
				+ "			<Mahuyen_NN>033</Mahuyen_NN>\r\n"
				+ "			<Maxa_NN>01135</Maxa_NN>\r\n"
				+ "			<Diachi_KS>0</Diachi_KS>\r\n"
				+ "			<Ten_ChaMe_Giamho>0</Ten_ChaMe_Giamho>\r\n"
				+ "			<MasoBHXH>130</MasoBHXH>\r\n"
				+ "			<Dienthoai_LH>0</Dienthoai_LH>\r\n"
				+ "			<Email_LH>0</Email_LH>\r\n"
				+ "			<CMND>0</CMND>\r\n"
				+ "			<Maho_Giadinh>0</Maho_Giadinh>\r\n"
				+ "			<Mucdong>0</Mucdong>\r\n"
				+ "			<Phuongthuc xsi:nil=\"true\"/>\r\n"
				+ "			<MaTinhBenhVien>01</MaTinhBenhVien>\r\n"
				+ "			<MaBenhVien>P09</MaBenhVien>\r\n"
				+ "			<Noidung_Thaydoi>0</Noidung_Thaydoi>\r\n"
				+ "			<HosoKemtheo>0</HosoKemtheo>\r\n"
				+ "			<CCNS>0</CCNS>\r\n"
				+ "			<ID>0000000008</ID>\r\n"
				+ "			<PhuLuc/>\r\n"
				+ "		</LaoDong>\r\n"
				+ "		<LaoDong>\r\n"
				+ "			<STT>9</STT>\r\n"
				+ "			<HoTen>0</HoTen>\r\n"
				+ "			<NgaySinh>19/03/2000</NgaySinh>\r\n"
				+ "			<GioiTinh>1</GioiTinh>\r\n"
				+ "			<DanToc>01</DanToc>\r\n"
				+ "			<QuocTich>VN</QuocTich>\r\n"
				+ "			<Matinh_KS>01</Matinh_KS>\r\n"
				+ "			<Mahuyen_KS>282</Mahuyen_KS>\r\n"
				+ "			<Maxa_KS>10477</Maxa_KS>\r\n"
				+ "			<Diachi_NN>0</Diachi_NN>\r\n"
				+ "			<Matinh_NN>01</Matinh_NN>\r\n"
				+ "			<Mahuyen_NN>282</Mahuyen_NN>\r\n"
				+ "			<Maxa_NN>10477</Maxa_NN>\r\n"
				+ "			<Diachi_KS>0</Diachi_KS>\r\n"
				+ "			<Ten_ChaMe_Giamho>0</Ten_ChaMe_Giamho>\r\n"
				+ "			<MasoBHXH>131</MasoBHXH>\r\n"
				+ "			<Dienthoai_LH>0</Dienthoai_LH>\r\n"
				+ "			<Email_LH>0</Email_LH>\r\n"
				+ "			<CMND>0</CMND>\r\n"
				+ "			<Maho_Giadinh>0</Maho_Giadinh>\r\n"
				+ "			<Mucdong>0</Mucdong>\r\n"
				+ "			<Phuongthuc xsi:nil=\"true\"/>\r\n"
				+ "			<MaTinhBenhVien>01</MaTinhBenhVien>\r\n"
				+ "			<MaBenhVien>P10</MaBenhVien>\r\n"
				+ "			<Noidung_Thaydoi>0</Noidung_Thaydoi>\r\n"
				+ "			<HosoKemtheo>0</HosoKemtheo>\r\n"
				+ "			<CCNS>0</CCNS>\r\n"
				+ "			<ID>0000000009</ID>\r\n"
				+ "			<PhuLuc/>\r\n"
				+ "		</LaoDong>\r\n"
				+ "		<LaoDong>\r\n"
				+ "			<STT>10</STT>\r\n"
				+ "			<HoTen>0</HoTen>\r\n"
				+ "			<NgaySinh>19/03/2000</NgaySinh>\r\n"
				+ "			<GioiTinh>1</GioiTinh>\r\n"
				+ "			<DanToc>01</DanToc>\r\n"
				+ "			<QuocTich>VN</QuocTich>\r\n"
				+ "			<Matinh_KS>01</Matinh_KS>\r\n"
				+ "			<Mahuyen_KS>016</Mahuyen_KS>\r\n"
				+ "			<Maxa_KS>00409</Maxa_KS>\r\n"
				+ "			<Diachi_NN>0</Diachi_NN>\r\n"
				+ "			<Matinh_NN>01</Matinh_NN>\r\n"
				+ "			<Mahuyen_NN>016</Mahuyen_NN>\r\n"
				+ "			<Maxa_NN>00409</Maxa_NN>\r\n"
				+ "			<Diachi_KS>0</Diachi_KS>\r\n"
				+ "			<Ten_ChaMe_Giamho>0</Ten_ChaMe_Giamho>\r\n"
				+ "			<MasoBHXH>132</MasoBHXH>\r\n"
				+ "			<Dienthoai_LH>0</Dienthoai_LH>\r\n"
				+ "			<Email_LH>0</Email_LH>\r\n"
				+ "			<CMND>0</CMND>\r\n"
				+ "			<Maho_Giadinh>0</Maho_Giadinh>\r\n"
				+ "			<Mucdong>0</Mucdong>\r\n"
				+ "			<Phuongthuc xsi:nil=\"true\"/>\r\n"
				+ "			<MaTinhBenhVien>01</MaTinhBenhVien>\r\n"
				+ "			<MaBenhVien>P11</MaBenhVien>\r\n"
				+ "			<Noidung_Thaydoi>0</Noidung_Thaydoi>\r\n"
				+ "			<HosoKemtheo>0</HosoKemtheo>\r\n"
				+ "			<CCNS>0</CCNS>\r\n"
				+ "			<ID>0000000010</ID>\r\n"
				+ "			<PhuLuc/>\r\n"
				+ "		</LaoDong>\r\n"
				+ "		<LaoDong>\r\n"
				+ "			<STT>11</STT>\r\n"
				+ "			<HoTen>0</HoTen>\r\n"
				+ "			<NgaySinh>19/03/2000</NgaySinh>\r\n"
				+ "			<GioiTinh>1</GioiTinh>\r\n"
				+ "			<DanToc>01</DanToc>\r\n"
				+ "			<QuocTich>VN</QuocTich>\r\n"
				+ "			<Matinh_KS>01</Matinh_KS>\r\n"
				+ "			<Mahuyen_KS>002</Mahuyen_KS>\r\n"
				+ "			<Maxa_KS>00055</Maxa_KS>\r\n"
				+ "			<Diachi_NN>0</Diachi_NN>\r\n"
				+ "			<Matinh_NN>01</Matinh_NN>\r\n"
				+ "			<Mahuyen_NN>002</Mahuyen_NN>\r\n"
				+ "			<Maxa_NN>00055</Maxa_NN>\r\n"
				+ "			<Diachi_KS>0</Diachi_KS>\r\n"
				+ "			<Ten_ChaMe_Giamho>0</Ten_ChaMe_Giamho>\r\n"
				+ "			<MasoBHXH>133</MasoBHXH>\r\n"
				+ "			<Dienthoai_LH>0</Dienthoai_LH>\r\n"
				+ "			<Email_LH>0</Email_LH>\r\n"
				+ "			<CMND>0</CMND>\r\n"
				+ "			<Maho_Giadinh>0</Maho_Giadinh>\r\n"
				+ "			<Mucdong>0</Mucdong>\r\n"
				+ "			<Phuongthuc xsi:nil=\"true\"/>\r\n"
				+ "			<MaTinhBenhVien>01</MaTinhBenhVien>\r\n"
				+ "			<MaBenhVien>P12</MaBenhVien>\r\n"
				+ "			<Noidung_Thaydoi>0</Noidung_Thaydoi>\r\n"
				+ "			<HosoKemtheo>0</HosoKemtheo>\r\n"
				+ "			<CCNS>0</CCNS>\r\n"
				+ "			<ID>0000000011</ID>\r\n"
				+ "			<PhuLuc/>\r\n"
				+ "		</LaoDong>\r\n"
				+ "		<LaoDong>\r\n"
				+ "			<STT>12</STT>\r\n"
				+ "			<HoTen>0</HoTen>\r\n"
				+ "			<NgaySinh>19/03/2000</NgaySinh>\r\n"
				+ "			<GioiTinh>1</GioiTinh>\r\n"
				+ "			<DanToc>01</DanToc>\r\n"
				+ "			<QuocTich>VN</QuocTich>\r\n"
				+ "			<Matinh_KS>02</Matinh_KS>\r\n"
				+ "			<Mahuyen_KS>033</Mahuyen_KS>\r\n"
				+ "			<Maxa_KS>01135</Maxa_KS>\r\n"
				+ "			<Diachi_NN>0</Diachi_NN>\r\n"
				+ "			<Matinh_NN>02</Matinh_NN>\r\n"
				+ "			<Mahuyen_NN>033</Mahuyen_NN>\r\n"
				+ "			<Maxa_NN>01135</Maxa_NN>\r\n"
				+ "			<Diachi_KS>0</Diachi_KS>\r\n"
				+ "			<Ten_ChaMe_Giamho>0</Ten_ChaMe_Giamho>\r\n"
				+ "			<MasoBHXH>134</MasoBHXH>\r\n"
				+ "			<Dienthoai_LH>0</Dienthoai_LH>\r\n"
				+ "			<Email_LH>0</Email_LH>\r\n"
				+ "			<CMND>0</CMND>\r\n"
				+ "			<Maho_Giadinh>0</Maho_Giadinh>\r\n"
				+ "			<Mucdong>0</Mucdong>\r\n"
				+ "			<Phuongthuc xsi:nil=\"true\"/>\r\n"
				+ "			<MaTinhBenhVien>01</MaTinhBenhVien>\r\n"
				+ "			<MaBenhVien>P13</MaBenhVien>\r\n"
				+ "			<Noidung_Thaydoi>0</Noidung_Thaydoi>\r\n"
				+ "			<HosoKemtheo>0</HosoKemtheo>\r\n"
				+ "			<CCNS>0</CCNS>\r\n"
				+ "			<ID>0000000012</ID>\r\n"
				+ "			<PhuLuc/>\r\n"
				+ "		</LaoDong>\r\n"
				+ "		<LaoDong>\r\n"
				+ "			<STT>13</STT>\r\n"
				+ "			<HoTen>0</HoTen>\r\n"
				+ "			<NgaySinh>19/03/2000</NgaySinh>\r\n"
				+ "			<GioiTinh>1</GioiTinh>\r\n"
				+ "			<DanToc>01</DanToc>\r\n"
				+ "			<QuocTich>VN</QuocTich>\r\n"
				+ "			<Matinh_KS>01</Matinh_KS>\r\n"
				+ "			<Mahuyen_KS>282</Mahuyen_KS>\r\n"
				+ "			<Maxa_KS>10477</Maxa_KS>\r\n"
				+ "			<Diachi_NN>0</Diachi_NN>\r\n"
				+ "			<Matinh_NN>01</Matinh_NN>\r\n"
				+ "			<Mahuyen_NN>282</Mahuyen_NN>\r\n"
				+ "			<Maxa_NN>10477</Maxa_NN>\r\n"
				+ "			<Diachi_KS>0</Diachi_KS>\r\n"
				+ "			<Ten_ChaMe_Giamho>0</Ten_ChaMe_Giamho>\r\n"
				+ "			<MasoBHXH>135</MasoBHXH>\r\n"
				+ "			<Dienthoai_LH>0</Dienthoai_LH>\r\n"
				+ "			<Email_LH>0</Email_LH>\r\n"
				+ "			<CMND>0</CMND>\r\n"
				+ "			<Maho_Giadinh>0</Maho_Giadinh>\r\n"
				+ "			<Mucdong>0</Mucdong>\r\n"
				+ "			<Phuongthuc xsi:nil=\"true\"/>\r\n"
				+ "			<MaTinhBenhVien>01</MaTinhBenhVien>\r\n"
				+ "			<MaBenhVien>P14</MaBenhVien>\r\n"
				+ "			<Noidung_Thaydoi>0</Noidung_Thaydoi>\r\n"
				+ "			<HosoKemtheo>0</HosoKemtheo>\r\n"
				+ "			<CCNS>0</CCNS>\r\n"
				+ "			<ID>0000000013</ID>\r\n"
				+ "			<PhuLuc/>\r\n"
				+ "		</LaoDong>\r\n"
				+ "		<LaoDong>\r\n"
				+ "			<STT>14</STT>\r\n"
				+ "			<HoTen>0</HoTen>\r\n"
				+ "			<NgaySinh>19/03/2000</NgaySinh>\r\n"
				+ "			<GioiTinh>1</GioiTinh>\r\n"
				+ "			<DanToc>01</DanToc>\r\n"
				+ "			<QuocTich>VN</QuocTich>\r\n"
				+ "			<Matinh_KS>01</Matinh_KS>\r\n"
				+ "			<Mahuyen_KS>016</Mahuyen_KS>\r\n"
				+ "			<Maxa_KS>00409</Maxa_KS>\r\n"
				+ "			<Diachi_NN>0</Diachi_NN>\r\n"
				+ "			<Matinh_NN>01</Matinh_NN>\r\n"
				+ "			<Mahuyen_NN>016</Mahuyen_NN>\r\n"
				+ "			<Maxa_NN>00409</Maxa_NN>\r\n"
				+ "			<Diachi_KS>0</Diachi_KS>\r\n"
				+ "			<Ten_ChaMe_Giamho>0</Ten_ChaMe_Giamho>\r\n"
				+ "			<MasoBHXH>136</MasoBHXH>\r\n"
				+ "			<Dienthoai_LH>0</Dienthoai_LH>\r\n"
				+ "			<Email_LH>0</Email_LH>\r\n"
				+ "			<CMND>0</CMND>\r\n"
				+ "			<Maho_Giadinh>0</Maho_Giadinh>\r\n"
				+ "			<Mucdong>0</Mucdong>\r\n"
				+ "			<Phuongthuc xsi:nil=\"true\"/>\r\n"
				+ "			<MaTinhBenhVien>01</MaTinhBenhVien>\r\n"
				+ "			<MaBenhVien>P15</MaBenhVien>\r\n"
				+ "			<Noidung_Thaydoi>0</Noidung_Thaydoi>\r\n"
				+ "			<HosoKemtheo>0</HosoKemtheo>\r\n"
				+ "			<CCNS>0</CCNS>\r\n"
				+ "			<ID>0000000014</ID>\r\n"
				+ "			<PhuLuc/>\r\n"
				+ "		</LaoDong>\r\n"
				+ "		<LaoDong>\r\n"
				+ "			<STT>15</STT>\r\n"
				+ "			<HoTen>0</HoTen>\r\n"
				+ "			<NgaySinh>19/03/2000</NgaySinh>\r\n"
				+ "			<GioiTinh>1</GioiTinh>\r\n"
				+ "			<DanToc>01</DanToc>\r\n"
				+ "			<QuocTich>VN</QuocTich>\r\n"
				+ "			<Matinh_KS>01</Matinh_KS>\r\n"
				+ "			<Mahuyen_KS>002</Mahuyen_KS>\r\n"
				+ "			<Maxa_KS>00055</Maxa_KS>\r\n"
				+ "			<Diachi_NN>0</Diachi_NN>\r\n"
				+ "			<Matinh_NN>01</Matinh_NN>\r\n"
				+ "			<Mahuyen_NN>002</Mahuyen_NN>\r\n"
				+ "			<Maxa_NN>00055</Maxa_NN>\r\n"
				+ "			<Diachi_KS>0</Diachi_KS>\r\n"
				+ "			<Ten_ChaMe_Giamho>0</Ten_ChaMe_Giamho>\r\n"
				+ "			<MasoBHXH>137</MasoBHXH>\r\n"
				+ "			<Dienthoai_LH>0</Dienthoai_LH>\r\n"
				+ "			<Email_LH>0</Email_LH>\r\n"
				+ "			<CMND>0</CMND>\r\n"
				+ "			<Maho_Giadinh>0</Maho_Giadinh>\r\n"
				+ "			<Mucdong>0</Mucdong>\r\n"
				+ "			<Phuongthuc xsi:nil=\"true\"/>\r\n"
				+ "			<MaTinhBenhVien>01</MaTinhBenhVien>\r\n"
				+ "			<MaBenhVien>P16</MaBenhVien>\r\n"
				+ "			<Noidung_Thaydoi>0</Noidung_Thaydoi>\r\n"
				+ "			<HosoKemtheo>0</HosoKemtheo>\r\n"
				+ "			<CCNS>0</CCNS>\r\n"
				+ "			<ID>0000000015</ID>\r\n"
				+ "			<PhuLuc/>\r\n"
				+ "		</LaoDong>\r\n"
				+ "		<LaoDong>\r\n"
				+ "			<STT>16</STT>\r\n"
				+ "			<HoTen>0</HoTen>\r\n"
				+ "			<NgaySinh>19/03/2000</NgaySinh>\r\n"
				+ "			<GioiTinh>1</GioiTinh>\r\n"
				+ "			<DanToc>01</DanToc>\r\n"
				+ "			<QuocTich>VN</QuocTich>\r\n"
				+ "			<Matinh_KS>02</Matinh_KS>\r\n"
				+ "			<Mahuyen_KS>033</Mahuyen_KS>\r\n"
				+ "			<Maxa_KS>01135</Maxa_KS>\r\n"
				+ "			<Diachi_NN>0</Diachi_NN>\r\n"
				+ "			<Matinh_NN>02</Matinh_NN>\r\n"
				+ "			<Mahuyen_NN>033</Mahuyen_NN>\r\n"
				+ "			<Maxa_NN>01135</Maxa_NN>\r\n"
				+ "			<Diachi_KS>0</Diachi_KS>\r\n"
				+ "			<Ten_ChaMe_Giamho>0</Ten_ChaMe_Giamho>\r\n"
				+ "			<MasoBHXH>138</MasoBHXH>\r\n"
				+ "			<Dienthoai_LH>0</Dienthoai_LH>\r\n"
				+ "			<Email_LH>0</Email_LH>\r\n"
				+ "			<CMND>0</CMND>\r\n"
				+ "			<Maho_Giadinh>0</Maho_Giadinh>\r\n"
				+ "			<Mucdong>0</Mucdong>\r\n"
				+ "			<Phuongthuc xsi:nil=\"true\"/>\r\n"
				+ "			<MaTinhBenhVien>01</MaTinhBenhVien>\r\n"
				+ "			<MaBenhVien>P16</MaBenhVien>\r\n"
				+ "			<Noidung_Thaydoi>0</Noidung_Thaydoi>\r\n"
				+ "			<HosoKemtheo>0</HosoKemtheo>\r\n"
				+ "			<CCNS>0</CCNS>\r\n"
				+ "			<ID>0000000016</ID>\r\n"
				+ "			<PhuLuc/>\r\n"
				+ "		</LaoDong>\r\n"
				+ "		<LaoDong>\r\n"
				+ "			<STT>17</STT>\r\n"
				+ "			<HoTen>0</HoTen>\r\n"
				+ "			<NgaySinh>19/03/2000</NgaySinh>\r\n"
				+ "			<GioiTinh>1</GioiTinh>\r\n"
				+ "			<DanToc>01</DanToc>\r\n"
				+ "			<QuocTich>VN</QuocTich>\r\n"
				+ "			<Matinh_KS>01</Matinh_KS>\r\n"
				+ "			<Mahuyen_KS>282</Mahuyen_KS>\r\n"
				+ "			<Maxa_KS>10477</Maxa_KS>\r\n"
				+ "			<Diachi_NN>0</Diachi_NN>\r\n"
				+ "			<Matinh_NN>01</Matinh_NN>\r\n"
				+ "			<Mahuyen_NN>282</Mahuyen_NN>\r\n"
				+ "			<Maxa_NN>10477</Maxa_NN>\r\n"
				+ "			<Diachi_KS>0</Diachi_KS>\r\n"
				+ "			<Ten_ChaMe_Giamho>0</Ten_ChaMe_Giamho>\r\n"
				+ "			<MasoBHXH>139</MasoBHXH>\r\n"
				+ "			<Dienthoai_LH>0</Dienthoai_LH>\r\n"
				+ "			<Email_LH>0</Email_LH>\r\n"
				+ "			<CMND>0</CMND>\r\n"
				+ "			<Maho_Giadinh>0</Maho_Giadinh>\r\n"
				+ "			<Mucdong>0</Mucdong>\r\n"
				+ "			<Phuongthuc xsi:nil=\"true\"/>\r\n"
				+ "			<MaTinhBenhVien>01</MaTinhBenhVien>\r\n"
				+ "			<MaBenhVien>P16</MaBenhVien>\r\n"
				+ "			<Noidung_Thaydoi>0</Noidung_Thaydoi>\r\n"
				+ "			<HosoKemtheo>0</HosoKemtheo>\r\n"
				+ "			<CCNS>0</CCNS>\r\n"
				+ "			<ID>0000000017</ID>\r\n"
				+ "			<PhuLuc/>\r\n"
				+ "		</LaoDong>\r\n"
				+ "		<LaoDong>\r\n"
				+ "			<STT>18</STT>\r\n"
				+ "			<HoTen>0</HoTen>\r\n"
				+ "			<NgaySinh>19/03/2000</NgaySinh>\r\n"
				+ "			<GioiTinh>1</GioiTinh>\r\n"
				+ "			<DanToc>01</DanToc>\r\n"
				+ "			<QuocTich>VN</QuocTich>\r\n"
				+ "			<Matinh_KS>01</Matinh_KS>\r\n"
				+ "			<Mahuyen_KS>016</Mahuyen_KS>\r\n"
				+ "			<Maxa_KS>00409</Maxa_KS>\r\n"
				+ "			<Diachi_NN>0</Diachi_NN>\r\n"
				+ "			<Matinh_NN>01</Matinh_NN>\r\n"
				+ "			<Mahuyen_NN>016</Mahuyen_NN>\r\n"
				+ "			<Maxa_NN>00409</Maxa_NN>\r\n"
				+ "			<Diachi_KS>0</Diachi_KS>\r\n"
				+ "			<Ten_ChaMe_Giamho>0</Ten_ChaMe_Giamho>\r\n"
				+ "			<MasoBHXH>0</MasoBHXH>\r\n"
				+ "			<Dienthoai_LH>0</Dienthoai_LH>\r\n"
				+ "			<Email_LH>0</Email_LH>\r\n"
				+ "			<CMND>0</CMND>\r\n"
				+ "			<Maho_Giadinh>0</Maho_Giadinh>\r\n"
				+ "			<Mucdong>0</Mucdong>\r\n"
				+ "			<Phuongthuc xsi:nil=\"true\"/>\r\n"
				+ "			<MaTinhBenhVien>01</MaTinhBenhVien>\r\n"
				+ "			<MaBenhVien>P16</MaBenhVien>\r\n"
				+ "			<Noidung_Thaydoi>0</Noidung_Thaydoi>\r\n"
				+ "			<HosoKemtheo>0</HosoKemtheo>\r\n"
				+ "			<CCNS>0</CCNS>\r\n"
				+ "			<ID>0000000018</ID>\r\n"
				+ "			<PhuLuc/>\r\n"
				+ "		</LaoDong>\r\n"
				+ "		<LaoDong>\r\n"
				+ "			<STT>19</STT>\r\n"
				+ "			<HoTen>0</HoTen>\r\n"
				+ "			<NgaySinh>19-03-2000</NgaySinh>\r\n"
				+ "			<GioiTinh>1</GioiTinh>\r\n"
				+ "			<DanToc>01</DanToc>\r\n"
				+ "			<QuocTich>VN</QuocTich>\r\n"
				+ "			<Matinh_KS>01</Matinh_KS>\r\n"
				+ "			<Mahuyen_KS>016</Mahuyen_KS>\r\n"
				+ "			<Maxa_KS>00409</Maxa_KS>\r\n"
				+ "			<Diachi_NN>0</Diachi_NN>\r\n"
				+ "			<Matinh_NN>01</Matinh_NN>\r\n"
				+ "			<Mahuyen_NN>016</Mahuyen_NN>\r\n"
				+ "			<Maxa_NN>00409</Maxa_NN>\r\n"
				+ "			<Diachi_KS>0</Diachi_KS>\r\n"
				+ "			<Ten_ChaMe_Giamho>0</Ten_ChaMe_Giamho>\r\n"
				+ "			<MasoBHXH>0</MasoBHXH>\r\n"
				+ "			<Dienthoai_LH>0</Dienthoai_LH>\r\n"
				+ "			<Email_LH>0</Email_LH>\r\n"
				+ "			<CMND>0</CMND>\r\n"
				+ "			<Maho_Giadinh>0</Maho_Giadinh>\r\n"
				+ "			<Mucdong>0</Mucdong>\r\n"
				+ "			<Phuongthuc xsi:nil=\"true\"/>\r\n"
				+ "			<MaTinhBenhVien>01</MaTinhBenhVien>\r\n"
				+ "			<MaBenhVien>P16</MaBenhVien>\r\n"
				+ "			<Noidung_Thaydoi>0</Noidung_Thaydoi>\r\n"
				+ "			<HosoKemtheo>0</HosoKemtheo>\r\n"
				+ "			<CCNS>0</CCNS>\r\n"
				+ "			<ID>0000000019</ID>\r\n"
				+ "			<PhuLuc/>\r\n"
				+ "		</LaoDong>\r\n"
				+ "	</NoiDung>\r\n"
				+ "</TK1-TS>";
		validateXMLSchemaStringXML(xsd, xml);
	}

}
